# Generated by Django 2.2.4 on 2019-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image',
            new_name='imageLink',
        ),
        migrations.AddField(
            model_name='player',
            name='roundNo',
            field=models.IntegerField(default=1),
        ),
    ]
