# Generated by Django 2.2.4 on 2020-01-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_player_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
    ]
