# Generated by Django 2.2.4 on 2020-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_player_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/audios'),
        ),
        migrations.AddField(
            model_name='clue',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='round',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/audios'),
        ),
        migrations.AddField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
