# Generated by Django 2.2.4 on 2020-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_auto_20201216_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isStaff',
            field=models.BooleanField(default=0),
        ),
    ]
