# Generated by Django 2.2.4 on 2020-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_player_isstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='leaderboard_freeze',
            field=models.BooleanField(default=0),
        ),
    ]
