# Generated by Django 2.2.4 on 2020-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_duration_leaderboard_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='leaderboard_hide',
            field=models.BooleanField(default=0),
        ),
    ]
