# Generated by Django 2.2.4 on 2021-12-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_duration_leaderboard_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='max_question',
            field=models.IntegerField(default=20),
        ),
    ]
